// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Membership_type is the predicate function for membership_type builders.
type Membership_type func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Personnel is the predicate function for personnel builders.
type Personnel func(*sql.Selector)

// PersonnelRelCustomer is the predicate function for personnelrelcustomer builders.
type PersonnelRelCustomer func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
