// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hmertakyatan/gymapi/ent/membership_type"
	"github.com/hmertakyatan/gymapi/ent/predicate"
)

// MembershipTypeUpdate is the builder for updating Membership_type entities.
type MembershipTypeUpdate struct {
	config
	hooks    []Hook
	mutation *MembershipTypeMutation
}

// Where appends a list predicates to the MembershipTypeUpdate builder.
func (mtu *MembershipTypeUpdate) Where(ps ...predicate.Membership_type) *MembershipTypeUpdate {
	mtu.mutation.Where(ps...)
	return mtu
}

// SetName sets the "name" field.
func (mtu *MembershipTypeUpdate) SetName(s string) *MembershipTypeUpdate {
	mtu.mutation.SetName(s)
	return mtu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mtu *MembershipTypeUpdate) SetNillableName(s *string) *MembershipTypeUpdate {
	if s != nil {
		mtu.SetName(*s)
	}
	return mtu
}

// SetDescription sets the "description" field.
func (mtu *MembershipTypeUpdate) SetDescription(s string) *MembershipTypeUpdate {
	mtu.mutation.SetDescription(s)
	return mtu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mtu *MembershipTypeUpdate) SetNillableDescription(s *string) *MembershipTypeUpdate {
	if s != nil {
		mtu.SetDescription(*s)
	}
	return mtu
}

// SetMembershipMonth sets the "membership_month" field.
func (mtu *MembershipTypeUpdate) SetMembershipMonth(u uint8) *MembershipTypeUpdate {
	mtu.mutation.ResetMembershipMonth()
	mtu.mutation.SetMembershipMonth(u)
	return mtu
}

// SetNillableMembershipMonth sets the "membership_month" field if the given value is not nil.
func (mtu *MembershipTypeUpdate) SetNillableMembershipMonth(u *uint8) *MembershipTypeUpdate {
	if u != nil {
		mtu.SetMembershipMonth(*u)
	}
	return mtu
}

// AddMembershipMonth adds u to the "membership_month" field.
func (mtu *MembershipTypeUpdate) AddMembershipMonth(u int8) *MembershipTypeUpdate {
	mtu.mutation.AddMembershipMonth(u)
	return mtu
}

// SetPrice sets the "price" field.
func (mtu *MembershipTypeUpdate) SetPrice(f float64) *MembershipTypeUpdate {
	mtu.mutation.ResetPrice()
	mtu.mutation.SetPrice(f)
	return mtu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (mtu *MembershipTypeUpdate) SetNillablePrice(f *float64) *MembershipTypeUpdate {
	if f != nil {
		mtu.SetPrice(*f)
	}
	return mtu
}

// AddPrice adds f to the "price" field.
func (mtu *MembershipTypeUpdate) AddPrice(f float64) *MembershipTypeUpdate {
	mtu.mutation.AddPrice(f)
	return mtu
}

// Mutation returns the MembershipTypeMutation object of the builder.
func (mtu *MembershipTypeUpdate) Mutation() *MembershipTypeMutation {
	return mtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mtu *MembershipTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mtu.sqlSave, mtu.mutation, mtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtu *MembershipTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := mtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mtu *MembershipTypeUpdate) Exec(ctx context.Context) error {
	_, err := mtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtu *MembershipTypeUpdate) ExecX(ctx context.Context) {
	if err := mtu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mtu *MembershipTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(membership_type.Table, membership_type.Columns, sqlgraph.NewFieldSpec(membership_type.FieldID, field.TypeUUID))
	if ps := mtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtu.mutation.Name(); ok {
		_spec.SetField(membership_type.FieldName, field.TypeString, value)
	}
	if value, ok := mtu.mutation.Description(); ok {
		_spec.SetField(membership_type.FieldDescription, field.TypeString, value)
	}
	if value, ok := mtu.mutation.MembershipMonth(); ok {
		_spec.SetField(membership_type.FieldMembershipMonth, field.TypeUint8, value)
	}
	if value, ok := mtu.mutation.AddedMembershipMonth(); ok {
		_spec.AddField(membership_type.FieldMembershipMonth, field.TypeUint8, value)
	}
	if value, ok := mtu.mutation.Price(); ok {
		_spec.SetField(membership_type.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := mtu.mutation.AddedPrice(); ok {
		_spec.AddField(membership_type.FieldPrice, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership_type.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mtu.mutation.done = true
	return n, nil
}

// MembershipTypeUpdateOne is the builder for updating a single Membership_type entity.
type MembershipTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MembershipTypeMutation
}

// SetName sets the "name" field.
func (mtuo *MembershipTypeUpdateOne) SetName(s string) *MembershipTypeUpdateOne {
	mtuo.mutation.SetName(s)
	return mtuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mtuo *MembershipTypeUpdateOne) SetNillableName(s *string) *MembershipTypeUpdateOne {
	if s != nil {
		mtuo.SetName(*s)
	}
	return mtuo
}

// SetDescription sets the "description" field.
func (mtuo *MembershipTypeUpdateOne) SetDescription(s string) *MembershipTypeUpdateOne {
	mtuo.mutation.SetDescription(s)
	return mtuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mtuo *MembershipTypeUpdateOne) SetNillableDescription(s *string) *MembershipTypeUpdateOne {
	if s != nil {
		mtuo.SetDescription(*s)
	}
	return mtuo
}

// SetMembershipMonth sets the "membership_month" field.
func (mtuo *MembershipTypeUpdateOne) SetMembershipMonth(u uint8) *MembershipTypeUpdateOne {
	mtuo.mutation.ResetMembershipMonth()
	mtuo.mutation.SetMembershipMonth(u)
	return mtuo
}

// SetNillableMembershipMonth sets the "membership_month" field if the given value is not nil.
func (mtuo *MembershipTypeUpdateOne) SetNillableMembershipMonth(u *uint8) *MembershipTypeUpdateOne {
	if u != nil {
		mtuo.SetMembershipMonth(*u)
	}
	return mtuo
}

// AddMembershipMonth adds u to the "membership_month" field.
func (mtuo *MembershipTypeUpdateOne) AddMembershipMonth(u int8) *MembershipTypeUpdateOne {
	mtuo.mutation.AddMembershipMonth(u)
	return mtuo
}

// SetPrice sets the "price" field.
func (mtuo *MembershipTypeUpdateOne) SetPrice(f float64) *MembershipTypeUpdateOne {
	mtuo.mutation.ResetPrice()
	mtuo.mutation.SetPrice(f)
	return mtuo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (mtuo *MembershipTypeUpdateOne) SetNillablePrice(f *float64) *MembershipTypeUpdateOne {
	if f != nil {
		mtuo.SetPrice(*f)
	}
	return mtuo
}

// AddPrice adds f to the "price" field.
func (mtuo *MembershipTypeUpdateOne) AddPrice(f float64) *MembershipTypeUpdateOne {
	mtuo.mutation.AddPrice(f)
	return mtuo
}

// Mutation returns the MembershipTypeMutation object of the builder.
func (mtuo *MembershipTypeUpdateOne) Mutation() *MembershipTypeMutation {
	return mtuo.mutation
}

// Where appends a list predicates to the MembershipTypeUpdate builder.
func (mtuo *MembershipTypeUpdateOne) Where(ps ...predicate.Membership_type) *MembershipTypeUpdateOne {
	mtuo.mutation.Where(ps...)
	return mtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mtuo *MembershipTypeUpdateOne) Select(field string, fields ...string) *MembershipTypeUpdateOne {
	mtuo.fields = append([]string{field}, fields...)
	return mtuo
}

// Save executes the query and returns the updated Membership_type entity.
func (mtuo *MembershipTypeUpdateOne) Save(ctx context.Context) (*Membership_type, error) {
	return withHooks(ctx, mtuo.sqlSave, mtuo.mutation, mtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtuo *MembershipTypeUpdateOne) SaveX(ctx context.Context) *Membership_type {
	node, err := mtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mtuo *MembershipTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := mtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuo *MembershipTypeUpdateOne) ExecX(ctx context.Context) {
	if err := mtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mtuo *MembershipTypeUpdateOne) sqlSave(ctx context.Context) (_node *Membership_type, err error) {
	_spec := sqlgraph.NewUpdateSpec(membership_type.Table, membership_type.Columns, sqlgraph.NewFieldSpec(membership_type.FieldID, field.TypeUUID))
	id, ok := mtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Membership_type.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membership_type.FieldID)
		for _, f := range fields {
			if !membership_type.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membership_type.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtuo.mutation.Name(); ok {
		_spec.SetField(membership_type.FieldName, field.TypeString, value)
	}
	if value, ok := mtuo.mutation.Description(); ok {
		_spec.SetField(membership_type.FieldDescription, field.TypeString, value)
	}
	if value, ok := mtuo.mutation.MembershipMonth(); ok {
		_spec.SetField(membership_type.FieldMembershipMonth, field.TypeUint8, value)
	}
	if value, ok := mtuo.mutation.AddedMembershipMonth(); ok {
		_spec.AddField(membership_type.FieldMembershipMonth, field.TypeUint8, value)
	}
	if value, ok := mtuo.mutation.Price(); ok {
		_spec.SetField(membership_type.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := mtuo.mutation.AddedPrice(); ok {
		_spec.AddField(membership_type.FieldPrice, field.TypeFloat64, value)
	}
	_node = &Membership_type{config: mtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership_type.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mtuo.mutation.done = true
	return _node, nil
}
