// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hmertakyatan/gymapi/ent/personnelrelcustomer"
	"github.com/hmertakyatan/gymapi/ent/predicate"
)

// PersonnelRelCustomerDelete is the builder for deleting a PersonnelRelCustomer entity.
type PersonnelRelCustomerDelete struct {
	config
	hooks    []Hook
	mutation *PersonnelRelCustomerMutation
}

// Where appends a list predicates to the PersonnelRelCustomerDelete builder.
func (prcd *PersonnelRelCustomerDelete) Where(ps ...predicate.PersonnelRelCustomer) *PersonnelRelCustomerDelete {
	prcd.mutation.Where(ps...)
	return prcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (prcd *PersonnelRelCustomerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, prcd.sqlExec, prcd.mutation, prcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (prcd *PersonnelRelCustomerDelete) ExecX(ctx context.Context) int {
	n, err := prcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (prcd *PersonnelRelCustomerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(personnelrelcustomer.Table, sqlgraph.NewFieldSpec(personnelrelcustomer.FieldID, field.TypeUUID))
	if ps := prcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, prcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	prcd.mutation.done = true
	return affected, err
}

// PersonnelRelCustomerDeleteOne is the builder for deleting a single PersonnelRelCustomer entity.
type PersonnelRelCustomerDeleteOne struct {
	prcd *PersonnelRelCustomerDelete
}

// Where appends a list predicates to the PersonnelRelCustomerDelete builder.
func (prcdo *PersonnelRelCustomerDeleteOne) Where(ps ...predicate.PersonnelRelCustomer) *PersonnelRelCustomerDeleteOne {
	prcdo.prcd.mutation.Where(ps...)
	return prcdo
}

// Exec executes the deletion query.
func (prcdo *PersonnelRelCustomerDeleteOne) Exec(ctx context.Context) error {
	n, err := prcdo.prcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{personnelrelcustomer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (prcdo *PersonnelRelCustomerDeleteOne) ExecX(ctx context.Context) {
	if err := prcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
