// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hmertakyatan/gymapi/ent/personnel"
	"github.com/hmertakyatan/gymapi/ent/personnelrelcustomer"
	"github.com/hmertakyatan/gymapi/ent/predicate"
)

// PersonnelQuery is the builder for querying Personnel entities.
type PersonnelQuery struct {
	config
	ctx                      *QueryContext
	order                    []personnel.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Personnel
	withPersonnelRelCustomer *PersonnelRelCustomerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PersonnelQuery builder.
func (pq *PersonnelQuery) Where(ps ...predicate.Personnel) *PersonnelQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PersonnelQuery) Limit(limit int) *PersonnelQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PersonnelQuery) Offset(offset int) *PersonnelQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PersonnelQuery) Unique(unique bool) *PersonnelQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PersonnelQuery) Order(o ...personnel.OrderOption) *PersonnelQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryPersonnelRelCustomer chains the current query on the "personnel_rel_customer" edge.
func (pq *PersonnelQuery) QueryPersonnelRelCustomer() *PersonnelRelCustomerQuery {
	query := (&PersonnelRelCustomerClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(personnel.Table, personnel.FieldID, selector),
			sqlgraph.To(personnelrelcustomer.Table, personnelrelcustomer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, personnel.PersonnelRelCustomerTable, personnel.PersonnelRelCustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Personnel entity from the query.
// Returns a *NotFoundError when no Personnel was found.
func (pq *PersonnelQuery) First(ctx context.Context) (*Personnel, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{personnel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PersonnelQuery) FirstX(ctx context.Context) *Personnel {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Personnel ID from the query.
// Returns a *NotFoundError when no Personnel ID was found.
func (pq *PersonnelQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{personnel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PersonnelQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Personnel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Personnel entity is found.
// Returns a *NotFoundError when no Personnel entities are found.
func (pq *PersonnelQuery) Only(ctx context.Context) (*Personnel, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{personnel.Label}
	default:
		return nil, &NotSingularError{personnel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PersonnelQuery) OnlyX(ctx context.Context) *Personnel {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Personnel ID in the query.
// Returns a *NotSingularError when more than one Personnel ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PersonnelQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{personnel.Label}
	default:
		err = &NotSingularError{personnel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PersonnelQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Personnels.
func (pq *PersonnelQuery) All(ctx context.Context) ([]*Personnel, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Personnel, *PersonnelQuery]()
	return withInterceptors[[]*Personnel](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PersonnelQuery) AllX(ctx context.Context) []*Personnel {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Personnel IDs.
func (pq *PersonnelQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(personnel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PersonnelQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PersonnelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PersonnelQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PersonnelQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PersonnelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PersonnelQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PersonnelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PersonnelQuery) Clone() *PersonnelQuery {
	if pq == nil {
		return nil
	}
	return &PersonnelQuery{
		config:                   pq.config,
		ctx:                      pq.ctx.Clone(),
		order:                    append([]personnel.OrderOption{}, pq.order...),
		inters:                   append([]Interceptor{}, pq.inters...),
		predicates:               append([]predicate.Personnel{}, pq.predicates...),
		withPersonnelRelCustomer: pq.withPersonnelRelCustomer.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithPersonnelRelCustomer tells the query-builder to eager-load the nodes that are connected to
// the "personnel_rel_customer" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PersonnelQuery) WithPersonnelRelCustomer(opts ...func(*PersonnelRelCustomerQuery)) *PersonnelQuery {
	query := (&PersonnelRelCustomerClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withPersonnelRelCustomer = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Personnel.Query().
//		GroupBy(personnel.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PersonnelQuery) GroupBy(field string, fields ...string) *PersonnelGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PersonnelGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = personnel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Personnel.Query().
//		Select(personnel.FieldName).
//		Scan(ctx, &v)
func (pq *PersonnelQuery) Select(fields ...string) *PersonnelSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PersonnelSelect{PersonnelQuery: pq}
	sbuild.label = personnel.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PersonnelSelect configured with the given aggregations.
func (pq *PersonnelQuery) Aggregate(fns ...AggregateFunc) *PersonnelSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PersonnelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !personnel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PersonnelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Personnel, error) {
	var (
		nodes       = []*Personnel{}
		_spec       = pq.querySpec()
		loadedTypes = [1]bool{
			pq.withPersonnelRelCustomer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Personnel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Personnel{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withPersonnelRelCustomer; query != nil {
		if err := pq.loadPersonnelRelCustomer(ctx, query, nodes,
			func(n *Personnel) { n.Edges.PersonnelRelCustomer = []*PersonnelRelCustomer{} },
			func(n *Personnel, e *PersonnelRelCustomer) {
				n.Edges.PersonnelRelCustomer = append(n.Edges.PersonnelRelCustomer, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PersonnelQuery) loadPersonnelRelCustomer(ctx context.Context, query *PersonnelRelCustomerQuery, nodes []*Personnel, init func(*Personnel), assign func(*Personnel, *PersonnelRelCustomer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Personnel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PersonnelRelCustomer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(personnel.PersonnelRelCustomerColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.personnel_personnel_rel_customer
		if fk == nil {
			return fmt.Errorf(`foreign-key "personnel_personnel_rel_customer" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "personnel_personnel_rel_customer" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *PersonnelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PersonnelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(personnel.Table, personnel.Columns, sqlgraph.NewFieldSpec(personnel.FieldID, field.TypeUUID))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personnel.FieldID)
		for i := range fields {
			if fields[i] != personnel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PersonnelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(personnel.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = personnel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PersonnelGroupBy is the group-by builder for Personnel entities.
type PersonnelGroupBy struct {
	selector
	build *PersonnelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PersonnelGroupBy) Aggregate(fns ...AggregateFunc) *PersonnelGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PersonnelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PersonnelQuery, *PersonnelGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PersonnelGroupBy) sqlScan(ctx context.Context, root *PersonnelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PersonnelSelect is the builder for selecting fields of Personnel entities.
type PersonnelSelect struct {
	*PersonnelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PersonnelSelect) Aggregate(fns ...AggregateFunc) *PersonnelSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PersonnelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PersonnelQuery, *PersonnelSelect](ctx, ps.PersonnelQuery, ps, ps.inters, v)
}

func (ps *PersonnelSelect) sqlScan(ctx context.Context, root *PersonnelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
